project_id = "pgbjqwdhtsinnaydijfj"

[functions.admin-invite]
verify_jwt = false

[functions.admin-invite-validate]
verify_jwt = false

[functions.admin-signup-accept]
verify_jwt = false

[functions.resend-admin-invite]
verify_jwt = false

[functions.manage-medications]
verify_jwt = true

[functions.manage-appointments]
verify_jwt = true