// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgbjqwdhtsinnaydijfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnYmpxd2RodHNpbm5heWRpamZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTQwMzYsImV4cCI6MjA3MTk3MDAzNn0.4SL2TtYswJVINvN0pFnp_jmGX64vp5HCjTXT9Hgy5y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});